# Pandas Dataframe Oluşturma

In [1]:
import pandas as pd

In [2]:
l = [1,2,39,67,90]

In [3]:
l

[1, 2, 39, 67, 90]

In [4]:
pd.DataFrame(l, columns = ["degisken_ismi"])

degisken_ismi
0              1
1              2
2             39
3             67
4             90

In [5]:
import numpy as np

In [7]:
m = np.arange(1,10).reshape(3,3)

In [8]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
pd.DataFrame(m, columns = ["var1", "var2", "var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [11]:
# df isimlendirme

In [12]:
df = pd.DataFrame(m, columns = ["var1", "var2", "var3"])

In [13]:
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [14]:
df.columns = ("deg1", "deg2", "deg3")

In [15]:
df

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [16]:
type(df)

pandas.core.frame.DataFrame

In [17]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [18]:
df.shape

(3, 3)

In [19]:
df.ndim

2

In [20]:
df.size

9

In [21]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
type(df.values)

numpy.ndarray

In [25]:
df.head(1)

deg1  deg2  deg3
0     1     2     3

In [26]:
df.tail(1)

deg1  deg2  deg3
2     7     8     9

In [27]:
a = np.array([1,2,3,4,5])

In [28]:
a

array([1, 2, 3, 4, 5])

In [29]:
pd.DataFrame(a, columns = ["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5